import type { Role } from "../context/AuthContext";

export interface MenuItem {
  label: string;
  path: string;
  icon: string;
  subNav?: MenuItem[];
  disabled?: boolean;
}

export const sidebarMenus: Record<Role, MenuItem[]> = {
  Admin: [
    { label: "Dashboard", path: "/admin", icon: "grid" },
    { label: "Projects", path: "/admin/projects", icon: "folder" },
    {
      label: "Invoices & Estimates",
      path: "/admin/invoices",
      icon: "file-text",
      subNav: [
        { label: "All Invoices", path: "/admin/invoices/all", icon: "list" },
        {
          label: "Owner",
          path: "/admin/quotations",
          icon: "user-check",
          subNav: [
            { label: "Quotation", path: "/admin/quotations", icon: "file-text" },
            { label: "Final Measurement", path: "/admin/measurements", icon: "tool" },
          ],
        },
        { label: "Labour", path: "/admin/invoices/all?type=labour", icon: "users" },
        { label: "Material", path: "/admin/invoices/all?type=material", icon: "package" },
      ],
    },
    {
      label: "User & Role Management",
      path: "/admin/users",
      icon: "users",
      subNav: [
        { label: "Users", path: "/admin/users", icon: "users" },
        { label: "Roles", path: "/admin/users/roles", icon: "user-check" },
        {
          label: "Permissions",
          path: "/admin/users/permissions",
          icon: "check-circle",
        },
      ],
    },
    { label: "Clients", path: "/admin/clients", icon: "user-check" },
    {
      label: "Owner Management",
      path: "/admin/owners",
      icon: "briefcase",
      subNav: [
        { label: "Owners List", path: "/admin/owners/list", icon: "list" },
        {
          label: "Agreements",
          path: "/admin/owners/agreements",
          icon: "file-text",
        },
        {
          label: "Track Payments",
          path: "/admin/owners/payments",
          icon: "credit-card",
        },
        {
          label: "Owner Ledger",
          path: "/admin/owners/ledger",
          icon: "book-open",
        },
      ],
    },
    { label: "AutoCAD Viewer", path: "/admin/autocad", icon: "layers" },
    { label: "Site Engineers", path: "/admin/engineers", icon: "tool" },
    {
      label: "Work & BOQ",
      path: "/admin/boq",
      icon: "clipboard",
      subNav: [
        { label: "BOQ Setup", path: "/admin/boq/setup", icon: "list" },
        {
          label: "Activity List",
          path: "/admin/boq/activities",
          icon: "activity",
        },
      ],
    },
    {
      label: "Material & Inventory",
      path: "/admin/inventory",
      icon: "package",
      subNav: [
        {
          label: "Material Master",
          path: "/admin/inventory/master",
          icon: "database",
        },
        {
          label: "Inventory Management",
          path: "/admin/inventory/stock",
          icon: "box",
        },
      ],
    },
    {
      label: "Finance & Accounts",
      path: "/admin/finance",
      icon: "dollar-sign",
      subNav: [
        {
          label: "Expenses",
          path: "/admin/finance/expenses",
          icon: "dollar-sign",
        },
        {
          label: "Profit Tracking",
          path: "/admin/finance/profit",
          icon: "trending-up",
        },
      ],
    },
    {
      label: "Approvals & Workflow",
      path: "/admin/approvals",
      icon: "check-circle",
      subNav: [
        {
          label: "Material Approval",
          path: "/admin/approvals/material",
          icon: "package",
        },
        {
          label: "Billing Approval",
          path: "/admin/approvals/billing",
          icon: "file-text",
        },
        {
          label: "Expense Approval",
          path: "/admin/approvals/expense",
          icon: "dollar-sign",
        },
      ],
    },
    {
      label: "Reports & Analytics",
      path: "/admin/reports",
      icon: "bar-chart",
      subNav: [
        {
          label: "Progress Report",
          path: "/admin/reports/progress",
          icon: "trending-up",
        },
        {
          label: "Financial Report",
          path: "/admin/reports/financial",
          icon: "dollar-sign",
        },
        { label: "Labour Report", path: "/admin/reports/labour", icon: "users" },
        {
          label: "Material Consumption",
          path: "/admin/reports/consumption",
          icon: "package",
        },
      ],
    },
    { label: "Notifications", path: "/admin/notifications", icon: "bell" },
    { label: "Documents", path: "/admin/documents", icon: "file-text" },
    {
      label: "Master Data",
      path: "/admin/master-data",
      icon: "database",
      subNav: [
        {
          label: "Material Master",
          path: "/admin/master-data/materials",
          icon: "package",
        },
        {
          label: "Labour Types",
          path: "/admin/master-data/labour",
          icon: "users",
        },
        {
          label: "Activity Types",
          path: "/admin/master-data/activities",
          icon: "list",
        },
        { label: "Units", path: "/admin/master-data/units", icon: "tool" },
      ],
    },
    { label: "Integrations", path: "/admin/integrations", icon: "link" },
    { label: "Chat", path: "/chat", icon: "message-circle" },
    { label: "Settings", path: "/admin/settings", icon: "settings" },
  ],
  ProjectManager: [
    { label: "Dashboard", path: "/manager", icon: "grid" },
    { label: "Projects", path: "/manager/projects", icon: "folder" },
    { label: "Work Progress", path: "/manager/work-progress", icon: "activity" },
    { label: "Tasks", path: "/manager/tasks", icon: "check-square" },
    {
      label: "Approvals",
      path: "/manager/approvals",
      icon: "check-circle",
      subNav: [
        { label: "DSR Approval", path: "/manager/approvals/dsr", icon: "clipboard-list" },
        { label: "Material Approval", path: "/manager/approvals/material", icon: "package" },
        { label: "Expense Approval", path: "/manager/approvals/expense", icon: "dollar-sign" },
      ],
    },
    { label: "BOQ", path: "/manager/boq", icon: "list" },
    { label: "Procurement", path: "/manager/procurement", icon: "shopping-cart" },
    { label: "Quality", path: "/manager/quality", icon: "shield-check" },
    { label: "Safety", path: "/manager/safety", icon: "alert-octagon" },
    {
      label: "Resources",
      path: "/manager/resources",
      icon: "users",
      subNav: [
        { label: "Deployment Hub", path: "/manager/resources/orchestrator", icon: "map" },
        { label: "Site Engineers", path: "/manager/projects", icon: "user-check" },
      ],
    },
    { label: "Labour", path: "/manager/labour", icon: "users" },
    {
      label: "Compliance Hub",
      path: "/manager/compliance",
      icon: "shield",
      subNav: [
        { label: "QC Governance", path: "/manager/compliance/qc", icon: "check-circle" },
        { label: "Safety Audit", path: "/manager/compliance/safety", icon: "alert-triangle" },
      ],
    },
    { label: "Chat", path: "/chat", icon: "message-circle" },
    { label: "Settings", path: "/manager/settings", icon: "settings" },
  ],
  SiteEngineer: [
    { label: "Dashboard", path: "/engineer", icon: "grid" },
    { label: "Daily Site Report (DSR)", path: "/engineer/dsr", icon: "clipboard" },
    {
      label: "Work Progress",
      path: "/engineer/progress",
      icon: "bar-chart",
      subNav: [
        { label: "Activity List", path: "/engineer/progress/activities", icon: "list" },
        { label: "Daily Progress Entry", path: "/engineer/progress/entry", icon: "clipboard" },
      ],
    },
    {
      label: "Labour Management",
      path: "/engineer/labor",
      icon: "users",
      subNav: [
        { label: "Labour Registry", path: "/engineer/labor/list", icon: "list" },
        { label: "Daily Attendance", path: "/engineer/labor/attendance", icon: "calendar" },
        { label: "Salary & Advances", path: "/engineer/labor/payments", icon: "dollar-sign" },
        { label: "Payroll Reports", path: "/engineer/labor/reports", icon: "file-text" },
      ],
    },
    {
      label: "Task Management",
      path: "/engineer/tasks",
      icon: "check-square",
    },
    {
      label: "Material Management",
      path: "/engineer/material/receipt",
      icon: "package",
      subNav: [
        { label: "Material Receipt", path: "/engineer/material/receipt", icon: "package" },
        { label: "Material Consumption", path: "/engineer/material/consumption", icon: "tool" },
        { label: "Stock Summary", path: "/engineer/material/stock", icon: "database" },
      ],
    },
    { label: "Machinery & Equipment", path: "/engineer/machinery", icon: "tool" },
    {
      label: "Quality Control (QC)",
      path: "/engineer/qc",
      icon: "check-circle",
      subNav: [
        { label: "Inspection", path: "/engineer/qc/inspection", icon: "search" },
        { label: "Test Reports", path: "/engineer/qc/reports", icon: "file-text" },
      ],
    },
    {
      label: "Safety Management",
      path: "/engineer/safety",
      icon: "alert-triangle",
      subNav: [
        { label: "Safety Checklist", path: "/engineer/safety/checklist", icon: "check-square" },
        { label: "Incident Report", path: "/engineer/safety/incident", icon: "file-text" },
      ],
    },
    { label: "Issue / Delay Tracker", path: "/engineer/issues", icon: "alert-triangle" },
    { label: "Site Photos", path: "/engineer/photos", icon: "camera" },
    { label: "Drawings & Documents", path: "/engineer/drawings", icon: "folder" },
    { label: "Checklists", path: "/engineer/checklists", icon: "list" },
    {
      label: "Approvals & Requests",
      path: "/engineer/approvals",
      icon: "check-circle",
      subNav: [
        { label: "Material Request", path: "/engineer/approvals/material", icon: "package" },
        { label: "Work Approval", path: "/engineer/approvals/work", icon: "check-circle" },
      ],
    },
    { label: "Reports", path: "/engineer/reports", icon: "bar-chart" },
    { label: "Chat", path: "/chat", icon: "message-circle" },
    { label: "Settings", path: "/engineer/settings", icon: "settings" },
  ],
  Accountant: [
    { label: "Dashboard", path: "/accountant", icon: "grid" },
    {
      label: "Chart of Accounts",
      path: "/accountant/chart-of-accounts/assets",
      icon: "book-open",
      subNav: [
        { label: "Assets", path: "/accountant/chart-of-accounts/assets", icon: "dollar-sign" },
        { label: "Liabilities", path: "/accountant/chart-of-accounts/liabilities", icon: "activity" },
        { label: "Income", path: "/accountant/chart-of-accounts/income", icon: "trending-up" },
        { label: "Expenses", path: "/accountant/chart-of-accounts/expenses", icon: "trending-down" },
      ],
    },
    {
      label: "Receivables",
      path: "/accountant/receivables/dashboard",
      icon: "trending-up",
      subNav: [
        {
          label: "Dashboard",
          path: "/accountant/receivables/dashboard",
          icon: "grid",
        },
        {
          label: "Invoices",
          path: "/accountant/receivables/invoices",
          icon: "file-text",
          subNav: [
            { label: "Create Invoice", path: "/accountant/receivables/invoices?sub=create", icon: "file-plus" },
            { label: "Invoice List", path: "/accountant/receivables/invoices?sub=list", icon: "list" },
            { label: "Invoice Approval", path: "/accountant/receivables/invoices?sub=approval", icon: "check-circle" },
          ],
        },
        {
          label: "Running Bills (RA Bills)",
          path: "/accountant/receivables/ra-bills",
          icon: "clipboard-list",
          subNav: [
            { label: "Create RA Bill", path: "/accountant/receivables/ra-bills?sub=create", icon: "file-plus" },
            { label: "RA Bill List", path: "/accountant/receivables/ra-bills?sub=list", icon: "list" },
            { label: "Bill Approval", path: "/accountant/receivables/ra-bills?sub=approval", icon: "check-circle" },
          ],
        },
        {
          label: "Credit Notes",
          path: "/accountant/receivables/credit-notes",
          icon: "rotate-ccw",
          subNav: [
            { label: "Create Credit Note", path: "/accountant/receivables/credit-notes?sub=create", icon: "file-plus" },
            { label: "Credit Note List", path: "/accountant/receivables/credit-notes?sub=list", icon: "list" },
          ],
        },
        {
          label: "Collections",
          path: "/accountant/receivables/collections",
          icon: "dollar-sign",
        },
        {
          label: "Client Ledger",
          path: "/accountant/receivables/client-ledger",
          icon: "book-open",
        },
        {
          label: "Reports",
          path: "/accountant/receivables/reports",
          icon: "bar-chart",
        },
      ],
    },
    {
      label: "Payables",
      path: "/accountant/payables/dashboard",
      icon: "shopping-cart",
      subNav: [
        {
          label: "Dashboard",
          path: "/accountant/payables/dashboard",
          icon: "grid",
        },
        {
          label: "Vendor Bills",
          path: "/accountant/payables/vendor-bills",
          icon: "truck",
          subNav: [
            { label: "Create Bill", path: "/accountant/payables/vendor-bills?sub=create", icon: "file-plus" },
            { label: "Bill List", path: "/accountant/payables/vendor-bills?sub=list", icon: "list" },
            { label: "Bill Approval", path: "/accountant/payables/vendor-bills?sub=approval", icon: "check-circle" },
            { label: "Bill Payment", path: "/accountant/payables/vendor-bills?sub=payments", icon: "dollar-sign" },
          ],
        },
        {
          label: "Contractor Bills",
          path: "/accountant/payables/contractor-bills",
          icon: "tool",
          subNav: [
            { label: "Create Bill", path: "/accountant/payables/contractor-bills?sub=create", icon: "file-plus" },
            { label: "Bill List", path: "/accountant/payables/contractor-bills?sub=list", icon: "list" },
            { label: "Bill Approval", path: "/accountant/payables/contractor-bills?sub=approval", icon: "check-circle" },
            { label: "Bill Payment", path: "/accountant/payables/contractor-bills?sub=payments", icon: "dollar-sign" },
          ],
        },
        {
          label: "Payment Requests",
          path: "/accountant/payables/payment-requests",
          icon: "credit-card",
        },
        {
          label: "Outstanding Payables",
          path: "/accountant/payables/outstanding",
          icon: "alert-circle",
        },
        {
          label: "Vendor Ledger",
          path: "/accountant/payables/vendor-ledger",
          icon: "book-open",
        },
        {
          label: "Contractor Ledger",
          path: "/accountant/payables/contractor-ledger",
          icon: "book",
        },
        {
          label: "Reports",
          path: "/accountant/payables/reports",
          icon: "bar-chart",
        },
      ],
    },
    {
      label: "Expenses",
      path: "/accountant/expenses/dashboard",
      icon: "dollar-sign",
      subNav: [
        { label: "Dashboard", path: "/accountant/expenses/dashboard", icon: "grid" },
        {
          label: "Direct Expenses",
          path: "/accountant/expenses/direct",
          icon: "activity",
          subNav: [
            { label: "Create Expense", path: "/accountant/expenses/direct?sub=create", icon: "file-plus" },
            { label: "Expense List", path: "/accountant/expenses/direct?sub=list", icon: "list" },
          ],
        },
        {
          label: "Indirect Expenses",
          path: "/accountant/expenses/indirect",
          icon: "briefcase",
          subNav: [
            { label: "Create Expense", path: "/accountant/expenses/indirect?sub=create", icon: "file-plus" },
            { label: "Expense List", path: "/accountant/expenses/indirect?sub=list", icon: "list" },
          ],
        },
        { label: "Expense Approval", path: "/accountant/expenses/approval", icon: "check-circle" },
        { label: "Expense Claims", path: "/accountant/expenses/claims", icon: "file-minus" },
        { label: "Project Cost Allocation", path: "/accountant/expenses/allocation", icon: "pie-chart" },
        { label: "Expense Ledger", path: "/accountant/expenses/ledger", icon: "book-open" },
        { label: "Reports", path: "/accountant/expenses/reports", icon: "bar-chart" },
      ],
    },
    {
      label: "Payments & Receipts",
      path: "/accountant/payments/dashboard",
      icon: "credit-card",
      subNav: [
        { label: "Dashboard", path: "/accountant/payments/dashboard", icon: "grid" },
        {
          label: "Receipts",
          path: "/accountant/payments/receipts",
          icon: "trending-up",
          subNav: [
            { label: "Record Receipt", path: "/accountant/payments/receipts?sub=create", icon: "plus-circle" },
            { label: "Receipts List", path: "/accountant/payments/receipts?sub=list", icon: "list" },
            { label: "Clearance", path: "/accountant/payments/receipts?sub=approval", icon: "check-circle" },
          ],
        },
        {
          label: "Payments",
          path: "/accountant/payments/payments",
          icon: "trending-down",
          subNav: [
            { label: "Make Payment", path: "/accountant/payments/payments?sub=create", icon: "minus-circle" },
            { label: "Payments List", path: "/accountant/payments/payments?sub=list", icon: "list" },
            { label: "Clearance", path: "/accountant/payments/payments?sub=approval", icon: "check-circle" },
          ],
        },
        { label: "Petty Cash", path: "/accountant/payments/petty-cash", icon: "dollar-sign" },
        { label: "Bank Transactions", path: "/accountant/payments/bank-transactions", icon: "briefcase" },
        { label: "Approvals", path: "/accountant/payments/approvals", icon: "check-circle" },
        { label: "Transaction Ledger", path: "/accountant/payments/ledger", icon: "book-open" },
        { label: "Reports", path: "/accountant/payments/reports", icon: "bar-chart" },
      ],
    },
    {
      label: "GST & Taxation",
      path: "/accountant/taxation/dashboard",
      icon: "percent",
      subNav: [
        { label: "Dashboard", path: "/accountant/taxation/dashboard", icon: "grid" },
        {
          label: "GST Invoices",
          path: "/accountant/taxation/invoices",
          icon: "file-text",
          subNav: [
            { label: "Sales Invoices", path: "/accountant/taxation/invoices?sub=sales", icon: "arrow-up-right" },
            { label: "Purchase Invoices", path: "/accountant/taxation/invoices?sub=purchase", icon: "arrow-down-left" },
            { label: "Register", path: "/accountant/taxation/invoices?sub=register", icon: "list" },
          ],
        },
        {
          label: "GST Returns",
          path: "/accountant/taxation/returns",
          icon: "bar-chart",
          subNav: [
            { label: "GSTR-1", path: "/accountant/taxation/returns?sub=gstr1", icon: "file" },
            { label: "GSTR-3B", path: "/accountant/taxation/returns?sub=gstr3b", icon: "file-text" },
            { label: "GSTR-2A", path: "/accountant/taxation/returns?sub=gstr2a", icon: "refresh-cw" },
            { label: "GSTR-2B", path: "/accountant/taxation/returns?sub=gstr2b", icon: "check-square" },
          ],
        },
        { label: "Input GST", path: "/accountant/taxation/input", icon: "download" },
        { label: "Output GST", path: "/accountant/taxation/output", icon: "upload" },
        { label: "TDS Management", path: "/accountant/taxation/tds", icon: "dollar-sign" },
        {
          label: "Reports",
          path: "/accountant/taxation/reports",
          icon: "pie-chart",
          subNav: [
            { label: "GST Summary", path: "/accountant/taxation/reports?sub=summary", icon: "file-text" },
            { label: "Input GST Report", path: "/accountant/taxation/reports?sub=input", icon: "download" },
            { label: "Output GST Report", path: "/accountant/taxation/reports?sub=output", icon: "upload" },
            { label: "TDS Report", path: "/accountant/taxation/reports?sub=tds", icon: "dollar-sign" },
            { label: "GST Return Report", path: "/accountant/taxation/reports?sub=return", icon: "refresh-cw" },
            { label: "Tax Audit Report", path: "/accountant/taxation/reports?sub=audit", icon: "shield" },
          ],
        },
      ],
    },
    {
      label: "Payroll",
      path: "/accountant/payroll/dashboard",
      icon: "users",
      subNav: [
        { label: "Dashboard", path: "/accountant/payroll/dashboard", icon: "grid" },
        {
          label: "Staff Salary",
          path: "/accountant/payroll/salary",
          icon: "briefcase",
          subNav: [
            { label: "Process Salary", path: "/accountant/payroll/salary?sub=process", icon: "play-circle" },
            { label: "Salary Register", path: "/accountant/payroll/salary?sub=register", icon: "list" },
            { label: "Payslips", path: "/accountant/payroll/salary?sub=payslips", icon: "file-text" },
            { label: "History", path: "/accountant/payroll/salary?sub=history", icon: "clock" },
          ],
        },
        {
          label: "Labor Wages",
          path: "/accountant/payroll/wages",
          icon: "activity",
          subNav: [
            { label: "Daily", path: "/accountant/payroll/wages?sub=daily", icon: "sun" },
            { label: "Weekly", path: "/accountant/payroll/wages?sub=weekly", icon: "calendar" },
            { label: "Monthly", path: "/accountant/payroll/wages?sub=monthly", icon: "moon" },
            { label: "Register", path: "/accountant/payroll/wages?sub=register", icon: "list" },
          ],
        },
        { label: "Contractor Payments", path: "/accountant/payroll/contractor", icon: "tool" },
        { label: "Attendance Integration", path: "/accountant/payroll/attendance", icon: "clock" },
        { label: "Advances & Deductions", path: "/accountant/payroll/advances", icon: "trending-down" },
        { label: "Approvals", path: "/accountant/payroll/approvals", icon: "check-square" },
        { label: "Payroll Ledger", path: "/accountant/payroll/ledger", icon: "book" },
        {
          label: "Reports",
          path: "/accountant/payroll/reports",
          icon: "pie-chart",
          subNav: [
            { label: "Salary Report", path: "/accountant/payroll/reports?sub=salary", icon: "file-text" },
            { label: "Labor Wage Report", path: "/accountant/payroll/reports?sub=wage", icon: "file" },
            { label: "Contractor Report", path: "/accountant/payroll/reports?sub=contractor", icon: "tool" },
            { label: "Attendance Report", path: "/accountant/payroll/reports?sub=attendance", icon: "clock" },
            { label: "Overtime Report", path: "/accountant/payroll/reports?sub=overtime", icon: "watch" },
            { label: "Payroll Summary", path: "/accountant/payroll/reports?sub=summary", icon: "pie-chart" },
          ],
        },
      ],
    },
    {
      label: "Bank & Cash",
      path: "/accountant/banking/dashboard",
      icon: "home",
      subNav: [
        { label: "Dashboard", path: "/accountant/banking/dashboard", icon: "grid" },
        {
          label: "Bank Accounts",
          path: "/accountant/banking/accounts",
          icon: "briefcase",
          subNav: [
            { label: "Add Account", path: "/accountant/banking/accounts?sub=add", icon: "plus-circle" },
            { label: "Account List", path: "/accountant/banking/accounts?sub=list", icon: "list" },
            { label: "Statements", path: "/accountant/banking/accounts?sub=statements", icon: "file-text" },
            { label: "Details", path: "/accountant/banking/accounts?sub=details", icon: "info" },
          ],
        },
        {
          label: "Cash Book",
          path: "/accountant/banking/cash",
          icon: "dollar-sign",
          subNav: [
            { label: "Cash Receipts", path: "/accountant/banking/cash?sub=receipts", icon: "arrow-down-left" },
            { label: "Cash Payments", path: "/accountant/banking/cash?sub=payments", icon: "arrow-up-right" },
            { label: "Petty Cash", path: "/accountant/banking/cash?sub=petty", icon: "coffee" },
            { label: "Cash Ledger", path: "/accountant/banking/cash?sub=ledger", icon: "book" },
          ],
        },
        {
          label: "Bank Reconciliation",
          path: "/accountant/banking/reconciliation",
          icon: "refresh-cw",
          subNav: [
            { label: "Dashboard", path: "/accountant/banking/reconciliation?sub=dashboard", icon: "grid" },
            { label: "Pending", path: "/accountant/banking/reconciliation?sub=pending", icon: "clock" },
            { label: "Matched", path: "/accountant/banking/reconciliation?sub=matched", icon: "check-circle" },
            { label: "History", path: "/accountant/banking/reconciliation?sub=history", icon: "clock" },
          ],
        },
        {
          label: "Fund Transfers",
          path: "/accountant/banking/transfers",
          icon: "repeat",
          subNav: [
            { label: "Bank to Bank", path: "/accountant/banking/transfers?sub=bank2bank", icon: "briefcase" },
            { label: "Bank to Cash", path: "/accountant/banking/transfers?sub=bank2cash", icon: "dollar-sign" },
            { label: "Cash to Bank", path: "/accountant/banking/transfers?sub=cash2bank", icon: "arrow-up-right" },
            { label: "History", path: "/accountant/banking/transfers?sub=history", icon: "clock" },
          ],
        },
        { label: "Transaction History", path: "/accountant/banking/history", icon: "list" },
        {
          label: "Reports",
          path: "/accountant/banking/reports",
          icon: "pie-chart",
          subNav: [
            { label: "Bank Book", path: "/accountant/banking/reports?sub=bankbook", icon: "book" },
            { label: "Cash Book", path: "/accountant/banking/reports?sub=cashbook", icon: "book-open" },
            { label: "Bank Reconciliation", path: "/accountant/banking/reports?sub=reconciliation", icon: "refresh-cw" },
            { label: "Fund Transfer", path: "/accountant/banking/reports?sub=transfer", icon: "repeat" },
            { label: "Cash Flow", path: "/accountant/banking/reports?sub=cashflow", icon: "trending-up" },
          ],
        },
      ],
    },
    {
      label: "Journal Entries",
      path: "/accountant/journal/dashboard",
      icon: "edit-3",
      subNav: [
        { label: "Dashboard", path: "/accountant/journal/dashboard", icon: "grid" },
        { label: "Manual Entry", path: "/accountant/journal/manual", icon: "edit" },
        {
          label: "Auto Entries",
          path: "/accountant/journal/auto",
          icon: "cpu",
          subNav: [
            { label: "Invoices", path: "/accountant/journal/auto?sub=invoices", icon: "file-text" },
            { label: "Vendor Bills", path: "/accountant/journal/auto?sub=bills", icon: "file" },
            { label: "Payroll", path: "/accountant/journal/auto?sub=payroll", icon: "users" },
            { label: "Payments", path: "/accountant/journal/auto?sub=payments", icon: "dollar-sign" },
            { label: "GST", path: "/accountant/journal/auto?sub=gst", icon: "pie-chart" },
          ],
        },
        { label: "Recurring Entries", path: "/accountant/journal/recurring", icon: "repeat" },
        { label: "Adjustment Entries", path: "/accountant/journal/adjustments", icon: "sliders" },
        { label: "Reversing Entries", path: "/accountant/journal/reversing", icon: "corner-up-left" },
        { label: "Journal Approval", path: "/accountant/journal/approval", icon: "check-circle" },
        { label: "Journal Register", path: "/accountant/journal/register", icon: "book" },
        { label: "Audit Trail", path: "/accountant/journal/audit", icon: "shield" },
        { label: "Reports", path: "/accountant/journal/reports", icon: "bar-chart-2" },
      ],
    },
    {
      label: "Fixed Assets",
      path: "/accountant/assets/dashboard",
      icon: "layers",
      subNav: [
        { label: "Dashboard", path: "/accountant/assets/dashboard", icon: "grid" },
        {
          label: "Asset Register",
          path: "/accountant/assets/register",
          icon: "box",
          subNav: [
            { label: "Add Asset", path: "/accountant/assets/register?sub=add", icon: "plus-circle" },
            { label: "Asset List", path: "/accountant/assets/register?sub=list", icon: "list" },
            { label: "Asset Details", path: "/accountant/assets/register?sub=details", icon: "info" },
            { label: "Asset Transfer", path: "/accountant/assets/register?sub=transfer", icon: "repeat" },
          ],
        },
        { label: "Asset Categories", path: "/accountant/assets/categories", icon: "tag" },
        {
          label: "Depreciation",
          path: "/accountant/assets/depreciation",
          icon: "trending-down",
          subNav: [
            { label: "Depreciation Setup", path: "/accountant/assets/depreciation?sub=setup", icon: "settings" },
            { label: "Monthly Depreciation", path: "/accountant/assets/depreciation?sub=monthly", icon: "calendar" },
            { label: "Annual Depreciation", path: "/accountant/assets/depreciation?sub=annual", icon: "calendar" },
            { label: "Depreciation History", path: "/accountant/assets/depreciation?sub=history", icon: "clock" },
          ],
        },
        {
          label: "Asset Maintenance",
          path: "/accountant/assets/maintenance",
          icon: "tool",
          subNav: [
            { label: "Maintenance Schedule", path: "/accountant/assets/maintenance?sub=schedule", icon: "calendar" },
            { label: "Service History", path: "/accountant/assets/maintenance?sub=history", icon: "clock" },
            { label: "Repair Cost", path: "/accountant/assets/maintenance?sub=cost", icon: "dollar-sign" },
            { label: "AMC Tracking", path: "/accountant/assets/maintenance?sub=amc", icon: "shield" },
          ],
        },
        {
          label: "Asset Transfers",
          path: "/accountant/assets/transfers",
          icon: "repeat",
          subNav: [
            { label: "Site Transfer", path: "/accountant/assets/transfers?sub=site", icon: "map-pin" },
            { label: "Department Transfer", path: "/accountant/assets/transfers?sub=department", icon: "users" },
            { label: "Asset Movement History", path: "/accountant/assets/transfers?sub=history", icon: "clock" },
          ],
        },
        {
          label: "Asset Disposal",
          path: "/accountant/assets/disposal",
          icon: "trash-2",
          subNav: [
            { label: "Asset Sale", path: "/accountant/assets/disposal?sub=sale", icon: "dollar-sign" },
            { label: "Asset Scrap", path: "/accountant/assets/disposal?sub=scrap", icon: "trash" },
            { label: "Asset Write-Off", path: "/accountant/assets/disposal?sub=writeoff", icon: "x-circle" },
          ],
        },
        { label: "Asset Ledger", path: "/accountant/assets/ledger", icon: "book" },
        { label: "Reports", path: "/accountant/assets/reports", icon: "bar-chart-2" },
      ],
    },
    {
      label: "Reports",
      path: "/accountant/reports/dashboard",
      icon: "bar-chart",
      subNav: [
        { label: "Dashboard", path: "/accountant/reports/dashboard", icon: "grid" },
        {
          label: "Financial Reports",
          path: "/accountant/reports/financial",
          icon: "dollar-sign",
          subNav: [
            { label: "Profit & Loss", path: "/accountant/reports/financial?sub=pl", icon: "trending-up" },
            { label: "Balance Sheet", path: "/accountant/reports/financial?sub=bs", icon: "columns" },
            { label: "Cash Flow", path: "/accountant/reports/financial?sub=cashflow", icon: "activity" },
            { label: "Trial Balance", path: "/accountant/reports/financial?sub=trial", icon: "check-square" },
            { label: "General Ledger", path: "/accountant/reports/financial?sub=ledger", icon: "book" },
            { label: "Journal Report", path: "/accountant/reports/financial?sub=journal", icon: "edit-3" },
          ],
        },
        {
          label: "Receivable Reports",
          path: "/accountant/reports/receivables",
          icon: "arrow-down-left",
          subNav: [
            { label: "Client Ledger", path: "/accountant/reports/receivables?sub=client", icon: "user" },
            { label: "Outstanding", path: "/accountant/reports/receivables?sub=outstanding", icon: "alert-circle" },
            { label: "Invoice Report", path: "/accountant/reports/receivables?sub=invoice", icon: "file-text" },
            { label: "RA Bill Report", path: "/accountant/reports/receivables?sub=rabill", icon: "file" },
            { label: "Collection Report", path: "/accountant/reports/receivables?sub=collection", icon: "download" },
            { label: "Credit Note Report", path: "/accountant/reports/receivables?sub=credit", icon: "minus-circle" },
          ],
        },
        {
          label: "Payable Reports",
          path: "/accountant/reports/payables",
          icon: "arrow-up-right",
          subNav: [
            { label: "Vendor Ledger", path: "/accountant/reports/payables?sub=vendor", icon: "users" },
            { label: "Contractor Ledger", path: "/accountant/reports/payables?sub=contractor", icon: "hard-hat" },
            { label: "Outstanding", path: "/accountant/reports/payables?sub=outstanding", icon: "alert-circle" },
            { label: "Vendor Bill Report", path: "/accountant/reports/payables?sub=bill", icon: "file" },
            { label: "Due Payment Report", path: "/accountant/reports/payables?sub=due", icon: "clock" },
          ],
        },
        {
          label: "Expense Reports",
          path: "/accountant/reports/expenses",
          icon: "shopping-cart",
          subNav: [
            { label: "Expense Summary", path: "/accountant/reports/expenses?sub=summary", icon: "pie-chart" },
            { label: "Project Expense", path: "/accountant/reports/expenses?sub=project", icon: "folder" },
            { label: "Category-wise Expense", path: "/accountant/reports/expenses?sub=category", icon: "tag" },
            { label: "Monthly Expense", path: "/accountant/reports/expenses?sub=monthly", icon: "calendar" },
            { label: "Site Expense", path: "/accountant/reports/expenses?sub=site", icon: "map-pin" },
          ],
        },
        {
          label: "Payroll Reports",
          path: "/accountant/reports/payroll",
          icon: "users",
          subNav: [
            { label: "Salary Report", path: "/accountant/reports/payroll?sub=salary", icon: "briefcase" },
            { label: "Labor Wage Report", path: "/accountant/reports/payroll?sub=wage", icon: "users" },
            { label: "Contractor Payment", path: "/accountant/reports/payroll?sub=contractor", icon: "hard-hat" },
            { label: "Attendance Report", path: "/accountant/reports/payroll?sub=attendance", icon: "calendar" },
            { label: "Overtime Report", path: "/accountant/reports/payroll?sub=overtime", icon: "clock" },
          ],
        },
        {
          label: "Asset Reports",
          path: "/accountant/reports/assets",
          icon: "layers",
          subNav: [
            { label: "Asset Register", path: "/accountant/reports/assets?sub=register", icon: "box" },
            { label: "Asset Valuation", path: "/accountant/reports/assets?sub=valuation", icon: "dollar-sign" },
            { label: "Depreciation Report", path: "/accountant/reports/assets?sub=depreciation", icon: "trending-down" },
            { label: "Asset Transfer Report", path: "/accountant/reports/assets?sub=transfer", icon: "repeat" },
            { label: "Maintenance Cost", path: "/accountant/reports/assets?sub=maintenance", icon: "tool" },
          ],
        },
        {
          label: "GST & Tax Reports",
          path: "/accountant/reports/taxes",
          icon: "pie-chart",
          subNav: [
            { label: "GST Report", path: "/accountant/reports/taxes?sub=gst", icon: "file-text" },
            { label: "Input GST Report", path: "/accountant/reports/taxes?sub=input", icon: "arrow-down-left" },
            { label: "Output GST Report", path: "/accountant/reports/taxes?sub=output", icon: "arrow-up-right" },
            { label: "TDS Report", path: "/accountant/reports/taxes?sub=tds", icon: "percent" },
            { label: "GST Reconciliation", path: "/accountant/reports/taxes?sub=recon", icon: "refresh-cw" },
            { label: "Tax Filing Report", path: "/accountant/reports/taxes?sub=filing", icon: "file" },
          ],
        },
        {
          label: "Project Cost Reports",
          path: "/accountant/reports/project",
          icon: "folder",
          subNav: [
            { label: "Budget vs Actual", path: "/accountant/reports/project?sub=budget", icon: "bar-chart" },
            { label: "Project Profitability", path: "/accountant/reports/project?sub=profit", icon: "trending-up" },
            { label: "Material Cost Report", path: "/accountant/reports/project?sub=material", icon: "box" },
            { label: "Labor Cost Report", path: "/accountant/reports/project?sub=labor", icon: "users" },
            { label: "Contractor Cost", path: "/accountant/reports/project?sub=contractor", icon: "hard-hat" },
            { label: "Equipment Cost", path: "/accountant/reports/project?sub=equipment", icon: "layers" },
            { label: "Cost Variance Report", path: "/accountant/reports/project?sub=variance", icon: "activity" },
          ],
        },
        {
          label: "Bank & Cash Reports",
          path: "/accountant/reports/banking",
          icon: "home",
          subNav: [
            { label: "Cash Book", path: "/accountant/reports/banking?sub=cash", icon: "book-open" },
            { label: "Bank Book", path: "/accountant/reports/banking?sub=bank", icon: "book" },
            { label: "Bank Reconciliation", path: "/accountant/reports/banking?sub=recon", icon: "refresh-cw" },
            { label: "Fund Transfer Report", path: "/accountant/reports/banking?sub=transfer", icon: "repeat" },
            { label: "Petty Cash Report", path: "/accountant/reports/banking?sub=petty", icon: "dollar-sign" },
          ],
        },
        {
          label: "MIS Reports",
          path: "/accountant/reports/mis",
          icon: "bar-chart-2",
          subNav: [
            { label: "Executive Dashboard", path: "/accountant/reports/mis?sub=dashboard", icon: "grid" },
            { label: "Monthly Financial Summary", path: "/accountant/reports/mis?sub=monthly", icon: "calendar" },
            { label: "Project Performance", path: "/accountant/reports/mis?sub=performance", icon: "activity" },
            { label: "Revenue vs Expense", path: "/accountant/reports/mis?sub=revexp", icon: "pie-chart" },
            { label: "Management MIS", path: "/accountant/reports/mis?sub=management", icon: "briefcase" },
          ],
        },
      ],
    },
    { label: "Chat", path: "/chat", icon: "message-circle" },
    {
      label: "Settings",
      path: "/accountant/settings/company",
      icon: "settings",
      subNav: [
        {
          label: "Company Settings",
          path: "/accountant/settings/company",
          icon: "briefcase",
          subNav: [
            { label: "Company Profile", path: "/accountant/settings/company?sub=profile", icon: "user" },
            { label: "Branches", path: "/accountant/settings/company?sub=branches", icon: "git-branch" },
            { label: "Departments", path: "/accountant/settings/company?sub=departments", icon: "users" },
            { label: "Company Documents", path: "/accountant/settings/company?sub=documents", icon: "file-text" },
          ],
        },
        {
          label: "Financial Settings",
          path: "/accountant/settings/financial",
          icon: "dollar-sign",
          subNav: [
            { label: "Financial Year", path: "/accountant/settings/financial?sub=year", icon: "calendar" },
            { label: "Currency", path: "/accountant/settings/financial?sub=currency", icon: "dollar-sign" },
            { label: "Fiscal Periods", path: "/accountant/settings/financial?sub=periods", icon: "clock" },
            { label: "Account Numbering", path: "/accountant/settings/financial?sub=numbering", icon: "hash" },
            { label: "Opening Balances", path: "/accountant/settings/financial?sub=balances", icon: "book-open" },
          ],
        },
        {
          label: "Tax Settings",
          path: "/accountant/settings/tax",
          icon: "pie-chart",
          subNav: [
            { label: "GST Configuration", path: "/accountant/settings/tax?sub=gst", icon: "file-text" },
            { label: "TDS Configuration", path: "/accountant/settings/tax?sub=tds", icon: "percent" },
            { label: "Tax Rates", path: "/accountant/settings/tax?sub=rates", icon: "activity" },
            { label: "Tax Rules", path: "/accountant/settings/tax?sub=rules", icon: "check-square" },
          ],
        },
        {
          label: "Invoice Settings",
          path: "/accountant/settings/invoice",
          icon: "file",
          subNav: [
            { label: "Invoice Format", path: "/accountant/settings/invoice?sub=format", icon: "layout" },
            { label: "Invoice Number Series", path: "/accountant/settings/invoice?sub=series", icon: "hash" },
            { label: "RA Bill Format", path: "/accountant/settings/invoice?sub=rabill", icon: "file-text" },
            { label: "Credit Note Format", path: "/accountant/settings/invoice?sub=credit", icon: "minus-circle" },
            { label: "PDF Templates", path: "/accountant/settings/invoice?sub=templates", icon: "printer" },
          ],
        },
        {
          label: "Payment Settings",
          path: "/accountant/settings/payment",
          icon: "credit-card",
          subNav: [
            { label: "Payment Terms", path: "/accountant/settings/payment?sub=terms", icon: "clock" },
            { label: "Bank Accounts", path: "/accountant/settings/payment?sub=banks", icon: "home" },
            { label: "Payment Modes", path: "/accountant/settings/payment?sub=modes", icon: "smartphone" },
            { label: "Auto Payment Rules", path: "/accountant/settings/payment?sub=auto", icon: "refresh-cw" },
          ],
        },
        {
          label: "Approval Workflow",
          path: "/accountant/settings/approval",
          icon: "check-circle",
          subNav: [
            { label: "Expense Approval", path: "/accountant/settings/approval?sub=expense", icon: "shopping-cart" },
            { label: "Purchase Approval", path: "/accountant/settings/approval?sub=purchase", icon: "shopping-bag" },
            { label: "Payroll Approval", path: "/accountant/settings/approval?sub=payroll", icon: "users" },
            { label: "Payment Approval", path: "/accountant/settings/approval?sub=payment", icon: "credit-card" },
            { label: "Journal Approval", path: "/accountant/settings/approval?sub=journal", icon: "book" },
          ],
        },
        {
          label: "User & Roles",
          path: "/accountant/settings/users",
          icon: "users",
          subNav: [
            { label: "Role Management", path: "/accountant/settings/users?sub=roles", icon: "shield" },
            { label: "User Permissions", path: "/accountant/settings/users?sub=permissions", icon: "key" },
            { label: "Access Control", path: "/accountant/settings/users?sub=access", icon: "lock" },
            { label: "Audit Logs", path: "/accountant/settings/users?sub=audit", icon: "list" },
          ],
        },
        {
          label: "Notification Settings",
          path: "/accountant/settings/notifications",
          icon: "bell",
          subNav: [
            { label: "Email Notifications", path: "/accountant/settings/notifications?sub=email", icon: "mail" },
            { label: "SMS Notifications", path: "/accountant/settings/notifications?sub=sms", icon: "message-square" },
            { label: "Due Date Alerts", path: "/accountant/settings/notifications?sub=alerts", icon: "clock" },
            { label: "Approval Alerts", path: "/accountant/settings/notifications?sub=approvals", icon: "check-circle" },
          ],
        },
        {
          label: "Document Settings",
          path: "/accountant/settings/documents",
          icon: "folder",
          subNav: [
            { label: "Attachment Rules", path: "/accountant/settings/documents?sub=rules", icon: "paperclip" },
            { label: "File Size Limits", path: "/accountant/settings/documents?sub=size", icon: "hard-drive" },
            { label: "Document Categories", path: "/accountant/settings/documents?sub=categories", icon: "tag" },
          ],
        },
        {
          label: "System Settings",
          path: "/accountant/settings/system",
          icon: "server",
          subNav: [
            { label: "Backup Settings", path: "/accountant/settings/system?sub=backup", icon: "database" },
            { label: "Data Import", path: "/accountant/settings/system?sub=import", icon: "download" },
            { label: "Data Export", path: "/accountant/settings/system?sub=export", icon: "upload" },
            { label: "System Preferences", path: "/accountant/settings/system?sub=preferences", icon: "sliders" },
          ],
        },
      ],
    },
  ],
  Client: [
    { label: "Dashboard", path: "/client", icon: "grid" },
    { label: "Project Overview", path: "/client/overview", icon: "info" },
    { label: "Work Progress", path: "/client/progress", icon: "bar-chart" },

    {
      label: "Site Updates",
      path: "/client/site-updates",
      icon: "camera",
      subNav: [
        { label: "Daily reports", path: "/client/site-updates/dsr", icon: "clipboard" },
        { label: "Photos", path: "/client/site-updates/photos", icon: "camera" },
      ],
    },
    { label: "Issues & Risks", path: "/client/issues", icon: "alert-triangle" },
    { label: "Documents & Drawings", path: "/client/documents", icon: "folder" },
    { label: "Approvals", path: "/client/approvals", icon: "check-circle" },
    {
      label: "Payment",
      path: "/client/payment",
      icon: "credit-card",
      subNav: [
        { label: "Quotation approval", path: "/client/payment/quotation", icon: "file-text" },
        { label: "Payment history", path: "/client/payment/history", icon: "clock" },
      ],
    },
    { label: "Chat", path: "/chat", icon: "message-circle" },
    { label: "Notifications", path: "/client/communication/announcements", icon: "bell" },
    {
      label: "Reports",
      path: "/client/reports",
      icon: "bar-chart",
      subNav: [
        { label: "Report Summary", path: "/client/reports/summary", icon: "file-text" },
        { label: "Financial Summary", path: "/client/reports/financial", icon: "dollar-sign" },
        { label: "Work Summary", path: "/client/reports/work", icon: "activity" },
      ],
    },
    { label: "Settings", path: "/client/settings", icon: "settings" },
  ],
  Labour: [
    { label: "Dashboard", path: "/labour", icon: "grid" },
    {
      label: "Attendance",
      path: "/labour/attendance",
      icon: "calendar",
    },
    { label: "My Tasks", path: "/labour/tasks", icon: "clipboard" },
    { label: "Work Updates", path: "/labour/work-updates", icon: "activity" },
    { label: "Task Requests", path: "/labour/task-requests", icon: "plus-circle" },
    { label: "Payments", path: "/labour/payments", icon: "wallet" },
    { label: "Chat", path: "/chat", icon: "message-circle" },
    { label: "Notifications", path: "/labour/notifications", icon: "bell" },
    { label: "Settings", path: "/labour/settings", icon: "settings" },
  ],
};
