import type { User } from "../types/user";

export const INITIAL_USERS: User[] = [
  {
    user_id: 1,
    full_name: "Rahul Sharma",
    email: "rahul.s@infrapilot.com",
    mobile_number: "+91 98765 43210",
    role: "Admin",
    designation: "System Administrator",
    pan_number: "ABCDE1234F",
    aadhaar_number: "1234 5678 9012",
    joining_date: "12 Jan 2024",
    address: "Pune, Maharashtra",
    is_active: true,
    profile_image: "https://i.pravatar.cc/150?u=rahul",
  },
  {
    user_id: 2,
    full_name: "Priya Patel",
    email: "priya.p@infrapilot.com",
    mobile_number: "+91 98765 43211",
    role: "ProjectManager",
    designation: "Senior Project Manager",
    pan_number: "FGHIJ5678K",
    aadhaar_number: "2345 6789 0123",
    joining_date: "15 Feb 2024",
    address: "Mumbai, Maharashtra",
    is_active: true,
    profile_image: "https://i.pravatar.cc/150?u=priya",
  },
  {
    user_id: 3,
    full_name: "Amit Kumar",
    email: "amit.k@infrapilot.com",
    mobile_number: "+91 98765 43212",
    role: "SiteEngineer",
    designation: "Civil Engineer",
    pan_number: "KLMNO9012P",
    aadhaar_number: "3456 7890 1234",
    joining_date: "10 Mar 2024",
    address: "Delhi, India",
    is_active: true,
    profile_image: "https://i.pravatar.cc/150?u=amit",
  },
  {
    user_id: 999,
    full_name: "Gopal Yadav",
    email: "gopal.y@infrapilot.com",
    mobile_number: "8888888888",
    role: "Labour",
    designation: "Head Mason",
    pan_number: "ABCDE9999Z",
    aadhaar_number: "9999 9999 9999",
    joining_date: "01 May 2024",
    address: "Lucknow, UP",
    is_active: true,
    profile_image: "https://i.pravatar.cc/150?u=gopal",
  },
];
