import { useState, useEffect } from "react";
import Navbar from "../../components/common/Navbar";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";
import { useClientProjectId } from "../../hooks/useClientProjectId";

const reportData = [
  { month: "Oct", progress: 15, cost: 1.2 },
  { month: "Nov", progress: 28, cost: 2.1 },
  { month: "Dec", progress: 42, cost: 3.4 },
  { month: "Jan", progress: 55, cost: 4.2 },
  { month: "Feb", progress: 62, cost: 4.8 },
  { month: "Mar", progress: 68, cost: 5.3 },
];

// ── PDF generator ─────────────────────────────────────────────────────────────
const downloadReport = (report: { name: string; date: string; type: string }) => {
  const generated = new Date().toLocaleString("en-IN");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>${report.name}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;900&display=swap');
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family:'Inter',sans-serif; background:#fff; color:#1e293b; padding:48px; }

    /* Header */
    .header { display:flex; justify-content:space-between; align-items:flex-start; border-bottom:3px solid #2563EB; padding-bottom:24px; margin-bottom:32px; }
    .logo h1  { font-size:22px; font-weight:900; color:#2563EB; letter-spacing:-0.5px; }
    .logo p   { font-size:10px; font-weight:700; color:#94a3b8; text-transform:uppercase; letter-spacing:2px; margin-top:4px; }
    .meta     { text-align:right; }
    .meta .badge { display:inline-block; background:#eff6ff; color:#2563EB; font-size:9px; font-weight:900; text-transform:uppercase; letter-spacing:1.5px; padding:4px 12px; border-radius:20px; margin-bottom:6px; }
    .meta p   { font-size:10px; color:#64748b; font-weight:600; margin-top:3px; }

    /* Title */
    .title-block { margin-bottom:32px; }
    .title-block h2 { font-size:20px; font-weight:900; color:#0f172a; }
    .title-block p  { font-size:11px; color:#64748b; font-weight:600; margin-top:6px; text-transform:uppercase; letter-spacing:1.5px; }

    /* Content Placeholder */
    .content { padding:40px; background:#f8fafc; border-radius:24px; border:1px solid #e2e8f0; text-align:center; margin-bottom:32px; }
    .content h3 { font-size:14px; font-weight:900; color:#1e293b; margin-bottom:12px; }
    .content p { font-size:12px; color:#64748b; line-height:1.6; }

    /* Footer */
    .footer { margin-top:40px; padding-top:20px; border-top:1px solid #e2e8f0; display:flex; justify-content:space-between; font-size:9px; color:#94a3b8; font-weight:700; text-transform:uppercase; letter-spacing:1px; }
  </style>
</head>
<body>

  <!-- Header -->
  <div class="header">
    <div class="logo">
      <h1>InfraPilot</h1>
      <p>Project Transparency Portal</p>
    </div>
    <div class="meta">
      <span class="badge">Official Report — ${report.type}</span>
      <p>Released: ${report.date}</p>
      <p>Generated: ${generated}</p>
    </div>
  </div>

  <!-- Title -->
  <div class="title-block">
    <h2>${report.name}</h2>
    <p>Comprehensive project documentation and audit summary</p>
  </div>

  <!-- Content -->
  <div class="content">
    <h3>Detailed Report Content</h3>
    <p>This is a formal project report generated by the InfraPilot Transparency Portal. <br/> 
       It contains detailed analytics, monthly performance summaries, and milestone verification data <br/> 
       pertinent to the construction progress and financial health of the project during the specified period.</p>
  </div>

  <!-- Analysis Placeholder -->
  <div style="font-size:11px; color:#475569; line-height:1.8; font-weight:500;">
    <strong>Verification Statement:</strong> The data presented in this report has been cross-verified with field logs, material invoices, 
    and onsite attendance records. All milestones reported as completed meet the project's quality standards and 
    technical specifications as of the release date.
  </div>

  <!-- Footer -->
  <div class="footer">
    <span>InfraPilot © 2026 — Project Transparency Portal</span>
    <span>CONFIDENTIAL | Page 1 of 1</span>
  </div>

</body>
</html>`;

  const iframe = document.createElement("iframe");
  iframe.style.cssText = "position:fixed;right:0;bottom:0;width:0;height:0;border:none;";
  document.body.appendChild(iframe);
  const doc = iframe.contentWindow?.document;
  if (!doc) return;
  doc.open();
  doc.write(html);
  doc.close();
  setTimeout(() => {
    iframe.contentWindow?.focus();
    iframe.contentWindow?.print();
    setTimeout(() => document.body.removeChild(iframe), 2000);
  }, 600);
};

const ClientReportsPage = () => (
  <>
    <Navbar title="Project Transparency Portal" breadcrumb={["InfraPilot", "Client", "Reports"]} />
    <div className="p-6 bg-slate-50 min-h-screen font-inter pb-12">
      <div className="mb-8">
        <h1 className="text-3xl font-black text-slate-800 tracking-tight">Project Reports</h1>
        <p className="text-slate-400 font-medium mt-1 uppercase tracking-widest text-[10px]">Detailed analytics & monthly performance summaries</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
        <div className="bg-white rounded-2xl p-8 shadow-sm border border-slate-100">
          <h2 className="text-[11px] font-black text-slate-800 uppercase tracking-widest mb-6">Progress Growth (Cumulative %)</h2>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={reportData}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                <XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: '#94a3b8', fontSize: 10, fontWeight: 700 }} />
                <YAxis axisLine={false} tickLine={false} tick={{ fill: '#94a3b8', fontSize: 10, fontWeight: 700 }} unit="%" />
                <Tooltip cursor={{ fill: '#f8fafc' }} contentStyle={{ borderRadius: '16px', border: 'none', boxShadow: '0 10px 30px rgba(0,0,0,0.1)' }} />
                <Bar dataKey="progress" fill="#2563EB" radius={[4, 4, 0, 0]} barSize={32} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="bg-white rounded-2xl p-8 shadow-sm border border-slate-100">
          <h2 className="text-[11px] font-black text-slate-800 uppercase tracking-widest mb-6">Cumulative Spent (₹ Cr)</h2>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={reportData}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                <XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: '#94a3b8', fontSize: 10, fontWeight: 700 }} />
                <YAxis axisLine={false} tickLine={false} tick={{ fill: '#94a3b8', fontSize: 10, fontWeight: 700 }} unit="Cr" />
                <Tooltip cursor={{ fill: '#f8fafc' }} contentStyle={{ borderRadius: '16px', border: 'none', boxShadow: '0 10px 30px rgba(0,0,0,0.1)' }} />
                <Bar dataKey="cost" fill="#6366F1" radius={[4, 4, 0, 0]} barSize={32} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      <div className="bg-white rounded-2xl p-8 shadow-sm border border-slate-100">
        <h2 className="text-[11px] font-black text-slate-800 uppercase tracking-widest mb-6">Monthly Report Archive</h2>
        <div className="space-y-3">
          {[
            { name: "Monthly Execution Report - March 2026", date: "02 Apr 2026", type: "PDF" },
            { name: "Financial Audit Report - Q1 2026", date: "25 Mar 2026", type: "PDF" },
            { name: "Safety & Compliance Audit - Feb 2026", date: "05 Mar 2026", type: "PDF" },
            { name: "Quality Control Summary - Jan 2026", date: "02 Feb 2026", type: "PDF" },
          ].map((item, i) => (
            <div
              key={i}
              onClick={() => downloadReport(item)}
              className="flex items-center justify-between p-4 bg-slate-50 rounded-2xl hover:bg-blue-50 transition-colors border border-transparent hover:border-blue-100 cursor-pointer group"
            >
              <div className="flex items-center gap-4">
                <div className="w-10 h-10 bg-white rounded-xl flex items-center justify-center text-red-500 font-black text-[10px] shadow-sm">{item.type}</div>
                <div>
                  <p className="text-sm font-bold text-slate-700">{item.name}</p>
                  <p className="text-[10px] text-slate-400 font-bold">{item.date}</p>
                </div>
              </div>
              <button className="p-2.5 bg-white rounded-xl text-blue-600 shadow-sm opacity-0 group-hover:opacity-100 transition-opacity">
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
              </button>
            </div>
          ))}
        </div>
      </div>
    </div>
  </>
);

export default ClientReportsPage;
